/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Akun;

import java.awt.Insets;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swingImageIcon;

/**
 *
 * @author AFFAN SALIM
 */
public class paymentPage extends javax.swing.JFrame {

    /**
     * Creates new form paymentPage
     */
    int mouseX,mouseY;
    
    
    public paymentPage() {
        initComponents();
        
        method.setMargin(new Insets(0,5,0,0));
        Topay.setMargin(new Insets(0,5,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Metod = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sb = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        method = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Cname = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        Topay = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        Metod.setBackground(new java.awt.Color(102, 153, 255));
        Metod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Metod.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel2.setText("GAMING GEAR");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 49, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Akun/image/icons8-pc-64.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 23, -1, -1));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel4.setText("GAMING FUNITURE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 54, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Akun/image/icons8-wing-chair-48.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(994, 39, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Akun/image/icons8-xbox-x-48.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 153, 255));
        jLabel8.setText("NUMG STORE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        Metod.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 130));

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Akun/image/icons8-pay-64.png"))); // NOI18N
        jLabel5.setText(" PAYMENT");
        Metod.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(":");
        Metod.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("-------");
        Metod.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 200, 60));

        sb.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        sb.setForeground(new java.awt.Color(255, 255, 255));
        sb.setText("0");
        Metod.add(sb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        jLabel19.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Back To Home?");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        Metod.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        method.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodActionPerformed(evt);
            }
        });
        Metod.add(method, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 200, 40));

        jLabel20.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Payment Method:");
        Metod.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Rp. ");
        Metod.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        jLabel22.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        Metod.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel24.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Sub Total ");
        Metod.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Metod.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 10, 390));

        Cname.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        Cname.setForeground(new java.awt.Color(255, 255, 255));
        Cname.setText("-");
        Metod.add(Cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BEST OF THE BEST PRICE & QUALITY");
        Metod.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 530, -1));

        jLabel9.setFont(new java.awt.Font("OCR A Extended", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NUMG STORE");
        Metod.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jButton1.setText("CANCEL\n\n");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Metod.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel27.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("LogOut?");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        Metod.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        Topay.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        Topay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopayActionPerformed(evt);
            }
        });
        Metod.add(Topay, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 200, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jButton3.setText("PAY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Metod.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jLabel28.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Total Pay ");
        Metod.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Customer Name ");
        Metod.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel23.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        Metod.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jLabel25.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
        Metod.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Metod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Metod, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do You Sure Wanna Leave?") == 0){
            this.dispose();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void methodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        mainPage main = new mainPage();
            
            main.setVisible(true);
            main.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mouseX= evt.getX();
        mouseY= evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - mouseX, y - mouseY);
        
    }//GEN-LAST:event_formMouseDragged

    private void TopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TopayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String can="";
        
        
        
        can+="Do You Sure Want To Leave Payment Page?";
        int result = JOptionPane.showConfirmDialog(null,can);
        
        if (result == JOptionPane.YES_OPTION){
             orderPage order = new orderPage();
            
            order.setVisible(true);
            order.setLocationRelativeTo(null);
            this.dispose();
            
        }
           
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String St = "";
        
        
        St += "========================================\n";
        St += "Name: "+Cname.getText()+"\n";
        St += "Payment Method: "+method.getText()+"\n";
        St += "Sub Total: "+sb.getText()+"\n";
        St += "Total Pay: Rp. "+Topay.getText()+"\n";
        St += "========================================\n";
        St += "Thank You For Purchase | Come Again :)\n";
        
        
        int hasil;
        
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/belajarjava4/image/icons8-checkmark-48.png"));
        
        JOptionPane.showMessageDialog(this,St, "Succes",JOptionPane.INFORMATION_MESSAGE, icon);
        
        this.dispose();
        
//        JOptionPane.showMessageDialog(this, St, "Succes",JOptionPane.INFORMATION_MESSAGE);
      
//        if(hasil == JOptionPane.YES_OPTION){
//            this.dispose();
//        }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        
        loginPage login = new loginPage();
            
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    public JLabel getCname() {
        return Cname;
    }

    public void setCname(JLabel Cname) {
        this.Cname = Cname;
    }

    public JTextField getTopay() {
        return Topay;
    }

    public void setTopay(JTextField Topay) {
        this.Topay = Topay;
    }

    public JLabel getSb() {
        return sb;
    }

    public void setSb(JLabel sb) {
        this.sb = sb;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Cname;
    private javax.swing.JPanel Metod;
    private javax.swing.JTextField Topay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField method;
    public javax.swing.JLabel sb;
    // End of variables declaration//GEN-END:variables
}
